project: generic-amd64
snaps:
  kernel: canonical-pc-linux
  os: ubuntu-core
  gadget: canonical-pc
configs:
  arch: amd64
  baseimage: base.img
  recoverytype: full
  recoverysize: 768
  release: 16
  channel: stable
  size: 4
udf:
  binary: ./ubuntu-device-flash
  option: core
debug:
  devmode: on
  ssh: on
  xz: off
recovery:
  filesystem-label: ESP
  boot-partition:
  systemboot-partition:
  writable-partition:
  boot-image:
  systemboot-image:
  writable-image:
